### ISSUE TITLE
You can't set the 'sslEnabled' setting unless you also set a non-default 'host'

### ISSUE THREAD

**Issue by DatL4g** [GitLiveApp/firebase-java-sdk#1]
As stated in https://github.com/GitLiveApp/firebase-java-sdk#limitations, Offline Persistence and SSL is not supported for Firestore.

Disabled SSL means we cannot use the default host `firestore.googleapis.com`, is there any alternative host we can use?
Could not find anything on the internet

**Comment by nbransby** [comment]
What error are you getting? It is used by others with standard Firebase

**Comment by DatL4g** [comment]
@nbransby forgot to mention that this only occurs on desktop, so android works fine.

The error message is the exact title after disabling ssl, however if I use default settings the desktop app crashes because it could not find an `Application` class or something like that, as this is android only.

Should be easy to create a simple reproducer, if you need more information hmu, but I'm on vacation right now so it could take a while

**Comment by nbransby** [comment]
I think you might be missing this https://github.com/GitLiveApp/firebase-java-sdk/blob/master/README.md#initializing-the-sdk

**Comment by DatL4g** [comment]
That actually works, used `Context` before and didn't know you exposed `Application` as well.
Can be quite confusing in multiplatform projects as they have the exact same package name.
