### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented in Desktop Version

### ISSUE THREAD

**Issue by dinesh-thiyagarajan** [GitLiveApp/firebase-java-sdk#20]
kotlin.NotImplementedError: An operation is not implemented . 

Getting this error for while trying to access Firebase.auth.currentUser?.email

**Comment by valeriyo** [comment]
That's what I just figured out - none of these are supported:

- `email`
- `isEmailVerified`
- `phoneNumber`
- `displayName`
- `photoURL`
- `metaData`

only `uid` works 😭  -- it's documented here, though:

https://github.com/GitLiveApp/firebase-java-sdk?tab=readme-ov-file#limitations

**Comment by dinesh-thiyagarajan** [comment]
@valeriyo thanks for the information. yeah it seems there are limitations for desktop versions.
