### ISSUE TITLE
0.4.7 is not published to maven

### ISSUE THREAD

**Issue by 89jd** [GitLiveApp/firebase-java-sdk#42]
Issue as per description, is this purposeful? I want to use the new firebase auth implementation

**Comment by nbransby** [comment]
Thanks for the head up, the CI failed, published now.

Although the only additional thing is support for auth emulator

**Comment by 89jd** [comment]
Yeh that is what I was wanting to use for Auth emulator 

Has it definitely published this time? Can still see the releases is showing 0.4.7 on GitHub and on mvn

**Comment by nbransby** [comment]
Is it there now?

**Comment by 89jd** [comment]
Yep can access it now!
